This project is build on Laravel has been used by multiple daycares around the world.
I stopped further development due to time constraints to focus on my fulltime job.
Your donation would help further development.

Also check out the CodeIgniter version

github: jgmuchiri
